name: Release C++
on:
  workflow_dispatch:
    inputs:
      version:
        description: VERSION
        required: true
jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Fetch Core library
      run: |
        version=${{ github.event.inputs.version }}
        wget https://github.com/inaccel/coral-api/releases/download/v${version%.*}/libcoral-api.so
    - name: Update (local) C++ version
      run: |
        scripts/version/cpp.sh ${{ github.event.inputs.version }}
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
        git commit --all --allow-empty --message 'C++ API v${{ github.event.inputs.version }}'
        git tag cpp-v${{ github.event.inputs.version }}
    - name: Package (Debian)
      uses: docker://goreleaser/nfpm
      with:
        args: pkg --packager deb
    - name: Package (RPM)
      uses: docker://goreleaser/nfpm
      env:
        RELEASE: 1
      with:
        args: pkg --packager rpm
    - name: Publish (Debian) to Cloudsmith
      uses: cloudsmith-io/action@master
      with:
        api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
        command: push
        format: deb
        owner: inaccel
        repo: stable
        distro: any-distro
        release: any-version
        file: '*.deb'
    - name: Publish (RPM) to Cloudsmith
      uses: cloudsmith-io/action@master
      with:
        api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
        command: push
        format: rpm
        owner: inaccel
        repo: stable
        distro: any-distro
        release: any-version
        file: '*.rpm'
    - name: Update (remote) C++ version
      run: |
        git push --atomic origin : cpp-v${{ github.event.inputs.version }}
