name: Documentation
on:
  push:
    branches:
    - master
    paths:
    - docs/**
jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        extended: true
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install dependencies
      working-directory: docs
      run: npm install autoprefixer postcss postcss-cli
    - name: Build
      working-directory: docs
      run: hugo --minify
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/public
        force_orphan: true
        full_commit_message: ${{ github.event.head_commit.id }}
