name: Release Python
on:
  workflow_dispatch:
    inputs:
      version:
        description: VERSION
        required: true
jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Fetch Core library
      run: |
        version=${{ github.event.inputs.version }}
        wget --directory-prefix src/main/python/inaccel/coral/native https://github.com/inaccel/coral-api/releases/download/v${version%.*}/libcoral-api.so
    - name: Update (local) Python version
      run: |
        scripts/version/python.sh ${{ github.event.inputs.version }}
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
        git commit --all --allow-empty --message 'Python API v${{ github.event.inputs.version }}'
        git tag python-v${{ github.event.inputs.version }}
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x
    - name: Install requirements
      run: pip install -r requirements.txt
    - name: Package
      run: python setup.py sdist bdist_wheel
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI }}
    - name: Update (remote) Python version
      run: |
        git push --atomic origin : python-v${{ github.event.inputs.version }}
