name: python
on: workflow_dispatch
jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build library (Core)
      uses: docker://inaccel/buildpack-deps:grpc
      with:
        entrypoint: make
        args: |
          src/main/python/inaccel/coral/native/libcoral-api.so
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Install requirements
      run: pip install -r requirements.txt
    - name: Package
      run: python setup.py sdist bdist_wheel
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.PYPI }}
